#+title: Notes on 'Pyramidial Flow Matching for Efficient Video Generative Modeling'

* Flow Matching for Generative Modeling:

** Abstract:
- Built on Continous Normalizing Flows (CFNs)
- Allows training CNFs at unprecedented scale
- Presents notion of flow matching (FM), a simulation-free approach for training CNFs based on regressing vector fields of fixed conditional probability paths.
- Compatible with general family of Gaussian probability paths for transforming between noise and data samples, which subsumes existing  diffusion paths as specific instances.
- Finds that employing FM with diffusion pths results in a more robust and stable alternative for training diffusion models
- Opens the dorr to training CNFs with other non-diffusion probability paths, such as Optimal Transport (OT) displacement interpolation to define the conditional probability paths

- These paths ar emore efficient than diffusion paths, provide faster training and sampling and result in better generalization.
- Training CNFs using Flow Matching on ImageNet leads to consistently better performance than alternative diffusion-based methods in terms of both likelihood and sample quality,
- Allows fast and reliable sample generation using off-the-shelf numerical ODE solvers

** Introduction:

** Preliminaries:

** Flow Matching:

** Conditional Probability Paths and Vector Fields:

** Related Work:




* Pyramidal Flow Matching for efficient video generative modeling:

** Abstract:

+ Video generation requires modeling a vast spatiotemporal space
  - this requires significant computational resources and data usage

+ To reduce complexity prevailing approaches employ a cascaded architecture
  - this avoids direct training with full resolution latents
    - the seperate optimization of each sub-stage hinder knowledge sharing and sacrifices flexibility.

+ introduces pyramidal flow matching algorithm
  - reinterprets denoising trajectory as a series of pyramid stages
    - only the final stage operates at full resolution
      - enabling more efficient video generative modeling

  - the flow of different pyramid stages can be interlinked to maintain continuity
  - craft autoregressive video generation with temporal pyramid to compress the full-resolution history
  - entire framework can be optimized in an end-to-end manner and with a sungle unified diffusion transformer
  - extensive experiments demonstate that the method supports generating  high-quality 5-seconds (up to 10s) videos at 768p resolution and 24 fps withing 20.7k A100 GPU training hours.

** Introduction:

- Teaching ai systems to generate various video content plays a vital role in simulating the real-world dynamics and interacting with humand.
- Cutting edge diffusion models and autoregressive models have made remarkable breakthroughs in generating realistic and long-duration video through scaling of data and computation
- However this necessitates modeling a significantely large spatiotemporal space, which makes the training of such video generative models computationally and data intensive.

- To ease the computational urden of generating high-dimensional video data, a crucial component is to compress the original video pixels into lower-dimensional latent space using VAE.
- However regular compression rates (typically 8x) still results in excessive tokens, especially for high-resolution samples
- Prevalent approaches utilize cascaded architecture to break down the high-resolution generation process into multiple stages, where samples are first created in a highly compressed latent space and then successively upsamples using additional super-resoultion models.
- Although this avoids directly learning at high resolution and reduces the computational demands, the requirement for exmploying distinct models at different resolutions separately sacrifices flexibility  and scalability
- Separate optimization of multiple sub-models also hinders the sharing of their acquired knowledge

- Paper presents an efficient video generative modeling framework that transcends the limiatations of previous casceded appoaches.
- Motivation stems from observation, that initial timesteps in diffusion models are quite noisy and uninformative
- This suggests that operating at full resolution throughout the entire generation trajectory may not be necessary
- To this end, the paper reinterpret the original generation trajectory as a series of pyramid stages that operate on compressed representations of different scales.
- Notably the efficacy of image pyramids has been widely validated for discriminative neural networks and more recently for diffusion models and multimodel LLMs.
- The paper investigates two types of pyramids:
  + the sptial pyramid within a frame
  + temporal one between consecutive frames
- In such as pyramidial generation trajectory  only the final stage operates at full resolution
- This drastically reduces redundant computation in earlier timesteps.
- Main advantages are:
  + generation trajectores of different pyramid stages are interlinked, with the subsequent stage continueing to generate from the previous ones, which eliminates the need for each stage to regenerate from pure noise in some cascade models
  + Instead of relying on separate models for each image pyramid, it integrates them into a single unified model for end-to-end optimization, which admits drastically-expedited training with more elegant implementation as validated by experiments

- Base on aforementiond pyromidal representation, the paper introduces novel pyramial flow-matching algorithm, that builds upon recent prevalent flow matching frameworks
- Specifically, the paper devises a piecewise flow for each pyramid resolution, which together form a generative process from noise to data.
- The flow withing each pyramid stage takes a similar formulation, interpolating between a picelated (compressed) and noisier latent and a pixelate-free (decompressed) and cleaner latent.
- Trough the design they can be jointly optimized by the unified flow matching objectve in a single Diffusion Transformer (DiT), allowing simultaneous generation and decompression of visual content without multiple separate models
- During inference the output of each stage is renoised by a correcitve Gaussian noise that maintains the continuity of the probality between stages
- Furthermore the paper formulates the video generation in an autoregressive manner, iteratively predicting the next video latent conditioned on the generated history.
- Given the high redundancy in the full-resolution history, the paper curates a temporal pyramid sequence using progressively compresser, lower-resolution history as conditions, which further reduces the number  of tokens and improving training efficiency.

- Collaboration of the spatial and temporal pyramids results in remarkable training efficiency for video generation
- Compared to commonly used full-sequence diffusion, the papers method significantely reduces the number of video tokens during training(e.g., <=15360 token vs. 119040 tokens for a 10s 241 frames video)
- Thereby reducing both computational  resouces required and training time
- By training only on open-source datasets the model generates a high-quality 10-second video at 768p resolution and 24fps

- Summarized:

+ pyramidal flow matching, a novel vieo generative modeling algorithm that incorporates both spatial and temporal pyramid representations. Utilizing this frameworks can significantely improve training efficiency while maintaining good video generative quality.

+ The proposed unified flow matching objective facilitates joint training of pyramid stages in a single Diffusion Transformer (DiT), avoiding the separate optimization of multiple models. The support for end-to-end training further enhances its simplicity and scalability.

+ We evaluate its effectiveness of VBench and EvalCrafter, with highly competitve performance among video generative models trained on public datasets.




** Related Work:
***  Video Generative Models:
- Rapid Progress with autoregressive models and diffusion models.
- Notable breakthrough is the high-didelity video diffusion models by scaling DiT pre-training, but they iduce significant training costs for long video
- Alternative line of research integrates diffusion models with autoregressive modeling to natively support long video generation but is still limited in context length and training efficiency.
- Paper advances both approaches in terms of efficiency from a compression perspective, featuring a spatially compressed pyramidal flow and temporally compressed pyramidal history.

*** Image Pyramids:
- Have been studied extensively in visual representation learning
- Idea is explored by cascaded diffusion models that first generate at low resolution and then perform super-resolution and later extended to video
- Requires training several separate models, which prevents knowledge sharing
- Unified modeling solutions for pyramids include hierachical architectures or via next-token prediction, but involve architecture changes
- Instead paper proposes a simple flow matching object that allows joint training of pyramids, thus facilitating efficient video generative modeling.

** Method:

** Experiments:


* PyramidWan: On Making Pretrained Video Model Pyramdial for Efficient Inference:

** Abstract:

-

** Introduction:
